### ISSUE TITLE
Prototype of the regulations editor

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-aeon-sketchbook#15]
The content of the first tab should be a regulations editor. This editor is based on cytoscape.js and this object https://github.com/sybila/biodivine-aeon-client/blob/master/script/CytoscapeEditor.js

The first goal is to try to take the existing functionality and port it to the new implementation. This includes:
 - Adding/removing nodes/regulations.
 - Drag-and-drop to re-layout nodes.
 - More or less the general style that is currently in use.
 - Floating menus for changing regulation/node properties (although some buttons can be disabled if the functionality does not exist yet).
 
Other stuff that involves updating the rest of the UI/app-state which is not the regulations editor can be skipped for now.

**Comment by ondrej33** [comment]
The frontend part is implemented thanks to #21 , #22 , #24. The backend part was addressed by #26.
